=== hbalazs11/Join-the-Adventure/xml_resources/xsd/JtaDescriptor.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- Created with Liquid Studio 2018 (https://www.liquid-technologies.com) -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="GameDescriptor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GameProperties" type="GamePropertiesType" minOccurs="0" />
                <xs:element name="Player" type="PlayerType" minOccurs="0" />
                <xs:element name="Rooms" type="RoomsType" minOccurs="0" />
                <xs:element name="MenuItems" type="MenuItemsType" minOccurs="0" maxOccurs="1" />
                <xs:element name="Items" type="ItemsType" minOccurs="0" maxOccurs="1" />
                <xs:element name="NPCs" type="NPCsType" minOccurs="0" />
                <xs:element name="Properties" type="PropertiesType" minOccurs="0" />
                <xs:element name="GameEnds" type="GameEndsType" minOccurs="0" />
                <xs:element name="Texts" type="TextsType" minOccurs="0" />
            </xs:sequence>
			<xs:attribute name="gameName" type="xs:string" use="required" />
            <xs:attribute name="version" type="xs:string" use="optional" />
            <xs:attribute name="id" type="xs:string" use="optional" />
            <xs:attribute name="root" default="false" type="xs:boolean" />
        </xs:complexType>
    </xs:element>
    <xs:complexType name="PlayerType">
        <xs:sequence>
            <xs:element name="Properties" type="PropertiesWithRefType" minOccurs="0" />
            <xs:element name="Items" type="ItemsWithRefsType" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RoomsType">
        <xs:sequence>
            <xs:element name="Room" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Properties" type="PropertiesWithRefType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="MenuItems" type="MenuItemsWithRefsType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Items" type="ItemsWithRefsType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="NPCs" type="NPCsWithRefType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Neighbours" type="NeighboursType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Texts" type="TextsType" minOccurs="0" maxOccurs="1" />
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required" />
                    <xs:attribute name="activeAtStart" default="true" type="xs:boolean" use="optional" />
                    <xs:attribute name="nameTextId" type="xs:string" use="required" />
                    <xs:attribute name="descTextId" type="xs:string" use="optional" />
                    <xs:attribute name="imgSrc" type="xs:string" use="required" />
                    <xs:attribute name="isCheckpoint" default="false" type="xs:boolean" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MenuItemsType">
        <xs:sequence>
            <xs:element name="MenuItem" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Requirements" type="RequirementsType" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Actions" type="ActionsType" minOccurs="1" maxOccurs="unbounded" />
                        <xs:element name="Texts" type="TextsType" minOccurs="0" />
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required" />
                    <xs:attribute name="activeAtStart" default="true" type="xs:boolean" use="optional" />
                    <xs:attribute name="useNumber" type="xs:integer" use="optional" />
                    <xs:attribute name="menuTextId" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MenuItemsWithRefsType">
        <xs:complexContent>
            <xs:extension base="MenuItemsType">
                <xs:sequence>
                    <xs:element name="MenuItemRef" type="ReferenceType" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ItemsType">
        <xs:sequence>
            <xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="MenuItems" type="MenuItemsType" minOccurs="0" />
                        <xs:element name="Properties" type="PropertiesWithRefType" minOccurs="0" />
                        <xs:element name="Texts" type="TextsType" minOccurs="0" />
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required" />
                    <xs:attribute name="activeAtStart" default="true" type="xs:boolean" use="optional" />
                    <xs:attribute name="equipable" default="false" type="xs:boolean" use="optional" />
                    <xs:attribute name="descTextId" type="xs:string" use="optional" />
                    <xs:attribute name="nameTextId" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ItemsWithRefsType">
        <xs:complexContent>
            <xs:extension base="ItemsType">
                <xs:sequence>
                    <xs:element name="ItemRef" type="ReferenceType" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TextsType">
        <xs:sequence>
            <xs:element name="Text" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="id" type="xs:string" use="required" />
                            <xs:attribute name="lang" type="xs:string" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="defLang" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="PropertiesType">
        <xs:sequence>
            <xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:string" use="required" />
                    <xs:attribute name="minValue" default="0" type="xs:double" use="optional" />
                    <xs:attribute name="maxValue" type="xs:double" use="optional" />
                    <xs:attribute name="defValue" default="0" type="xs:double" use="optional" />
                    <xs:attribute name="nameTextId" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PropertiesWithRefType">
        <xs:complexContent>
            <xs:extension base="PropertiesType">
                <xs:sequence>
                    <xs:element name="PropertyRef" type="ReferenceType" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="PropertyConditionEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="eq" />
            <xs:enumeration value="lt" />
            <xs:enumeration value="gt" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="PropertyChangeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="set" />
            <xs:enumeration value="dec" />
            <xs:enumeration value="inc" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ActivationSetEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true" />
            <xs:enumeration value="false" />
            <xs:enumeration value="switch" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ReferenceType">
        <xs:attribute name="refId" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="GamePropertiesType">
        <xs:attribute name="firstRoomId" type="xs:string" use="required" />
        <xs:attribute name="gameNameTextId" type="xs:string" use="required" />
        <xs:attribute name="greetingTextId" type="xs:string" />
        <xs:attribute name="checkpointsOn" default="false" type="xs:boolean" />
        <xs:attribute name="defaultLang" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="NPCsType">
        <xs:sequence>
            <xs:element name="NPC" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Conversation" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Line" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Answer" minOccurs="0" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="Requirements" type="RequirementsType" minOccurs="0" />
                                                            <xs:element name="Actions" type="ItemActionsType" minOccurs="0" />
                                                        </xs:sequence>
                                                        <xs:attribute name="id" type="xs:string" use="required" />
                                                        <xs:attribute name="activeAtStart" default="true" type="xs:boolean" />
                                                        <xs:attribute name="textId" type="xs:string" use="required" />
                                                        <xs:attribute name="nextLineId" type="xs:string" use="required" />
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="id" type="xs:string" use="required" />
                                            <xs:attribute name="lineTextId" type="xs:string" use="required" />
                                            <xs:attribute name="isLastLine" type="xs:boolean" default="false" />
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Requirements" type="RequirementsType" minOccurs="0" />
                                    <xs:element name="Texts" type="TextsType" minOccurs="0" />
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:string" use="required" />
                                <xs:attribute name="activeAtStart" type="xs:boolean" />
                                <xs:attribute name="firstLineId" type="xs:string" use="required" />
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="MenuItems" type="MenuItemsWithRefsType" minOccurs="0" />
                        <xs:element name="Items" type="ItemsWithRefsType" minOccurs="0" />
                        <xs:element name="Texts" type="TextsType" minOccurs="0" />
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required" />
                    <xs:attribute name="nameTextId" type="xs:string" use="required" />
                    <xs:attribute name="descTextId" type="xs:string" />
                    <xs:attribute name="activeAtStart" type="xs:boolean" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NPCsWithRefType">
        <xs:complexContent>
            <xs:extension base="NPCsType">
                <xs:sequence>
                    <xs:element name="NPCRef" type="ReferenceType" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ActionsType">
        <xs:sequence>
            <xs:element name="setActive" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="refId" type="xs:string" use="required" />
                    <xs:attribute name="value" type="ActivationSetEnum" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="setPropertyValue" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="refId" type="xs:string" use="required" />
                    <xs:attribute name="change" type="PropertyChangeEnum" use="required" />
                    <xs:attribute name="value" type="xs:double" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="responseTextId" type="xs:string" use="required" />
        <xs:attribute name="onUseIntervalTo" type="xs:integer" use="optional" default="0" />
    </xs:complexType>
    <xs:complexType name="ItemActionsType">
        <xs:complexContent>
            <xs:extension base="ActionsType">
                <xs:sequence>
                    <xs:element name="equipItem" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="refId" type="xs:string" use="required" />
                            <xs:attribute name="value" type="xs:boolean" default="true" />
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="RequirementsType">
        <xs:sequence>
            <xs:element name="isActive" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="refId" type="xs:string" use="required" />
                    <xs:attribute name="value" type="xs:boolean" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="propertyCondition" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="refId" type="xs:string" use="required" />
                    <xs:attribute name="condition" type="PropertyConditionEnum" use="required" />
                    <xs:attribute name="value" type="xs:double" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="isEquipped" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="refId" type="xs:string" use="required" />
                    <xs:attribute name="value" type="xs:boolean" use="optional" default="true" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="textOnFail" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="GameEndsType">
        <xs:sequence>
            <xs:element name="GameEnd" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:string" use="required" />
                    <xs:attribute name="textId" type="xs:string" use="required" />
                    <xs:attribute name="gameOverTextId" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NeighboursType">
        <xs:sequence>
            <xs:element name="Neighbour" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Requirements" type="RequirementsType" minOccurs="0" maxOccurs="1" />
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required" />
                    <xs:attribute name="roomRefId" type="xs:string" use="required" />
                    <xs:attribute name="nameTextId" type="xs:string" use="required" />
                    <xs:attribute name="activeAtStart" default="true" type="xs:boolean" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== hbalazs11/Join-the-Adventure/games/FredInSpace/jtaLabelsHun.xml
<?xml version="1.0" encoding="utf-8" ?>
<GameDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="JtaDescriptor.xsd" id="hunJtaLabels" root="false" gameName="FredInSpace">
  <Texts defLang="hun">
    <Text id="jtaLabelInventory">Eszközeim</Text>
    <Text id="jtaLabelGoNextRoom">Továbbhaladás...</Text>
    <Text id="jtaLabelMenu">Menü</Text>
    <Text id="jtaLabelPickUp">Eltesz</Text>
    <Text id="jtaLabelBack">Vissza</Text>
    <Text id="jtaLabelItems">Eszközök</Text>
    <Text id="jtaLabelPickUpNotif">Eltetted a következőt:</Text>
    <Text id="jtaLabelNpc">Személyek</Text>
    <Text id="jtaLabelShowDescription">Megnézem magamnak...</Text>
    <Text id="jtaLabelStartConversation">Odamegyek hozzá...</Text>
    <Text id="jtaLabelConversationWith">Beszélgetés vele: </Text>
    <Text id="jtaLabelLoad">Betöltés</Text>
    <Text id="jtaLabelSave">Mentés</Text>
    <Text id="jtaLabelExit">Kilépés</Text>
    <Text id="jtaLabelLanguages">Nyelvek</Text>
    <Text id="jtaLabelSavedGames">Mentések</Text>
    <Text id="jtaLabelSavedName">Mentés név...</Text>
    <Text id="jtaLabelEmptyItemList">Itt nincs semmi...</Text>
    <Text id="jtaLabelEmptyNeighbourList">Innen nincs kiút</Text>
    <Text id="jtaLabelEmptyNpcList">Itt nincs kivel beszélni...</Text>
    <Text id="jtaLabelPlayerProprs">Értékeim</Text>
    <Text id="jtaLabelItemProprs">Tulajdonságok</Text>
    <Text id="jtaLabelNpcProprs">Tulajdonságok</Text>
  </Texts>
</GameDescriptor>

=== hbalazs11/Join-the-Adventure/xml_resources/examples/AwesomeTestGameToLoad/TextsEng.xml
<?xml version="1.0" encoding="utf-8" ?>
<GameDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="JtaDescriptor.xsd"
                version="1" id="engText" root="false">
  <Texts defLang="eng">
    <Text id="playerHealthNameTxt">Hitpoints</Text>
    <Text id="torchNameTxt">Torch</Text>
    <Text id="torchDescTxt">This is a simple torch. There is a switch on it.</Text>
    <Text id="torchSwitchOnMenuTxt">Turn on</Text>
    <Text id="torchSwitchOnResponseTxt">You have turned on the torch.</Text>
    <Text id="torchSwitchOffMenuTxt">Turn off</Text>
    <Text id="torchSwitchOffResponseTxt">You have turned off the torch.</Text>
    <Text id="torchSwitchNameTxt">Torch</Text>
    <Text id="smallRoomNameTxt">Small room</Text>
    <Text id="smallRoomDescTxt">This is a simple small room. The light is weak, and it is really dark in the corners.</Text>
    <Text id="searchRoomMenuTxt">Look around</Text>
    <Text id="searchFailedTxt">You have found nothing interesting!</Text>
    <Text id="searchSucceededTxt">In the datk corner, a thing sparks in the light of the torch. It's a key!</Text>
    <Text id="doorKeyNameTxt">Key</Text>
    <Text id="neighbourSmallToBigMenuTxt">Through the door</Text>
    <Text id="doorIsClosedTxt">The door is locked.</Text>
    <Text id="blacksmithLine1Txt">Wellcome in my room!\nNow you have came so far, here is something for You!\nDo you want the pear or the apple?</Text>
    <Text id="pearAnswTxt">I want the pear!</Text>
    <Text id="appleAnswTxt">I want the apple!</Text>
    <Text id="takePearTxt">You have put the pear into your bag.</Text>
    <Text id="takeAppleTxt">You have put the apple into your bag.</Text>
    <Text id="blacksmithLine2Txt">I have nothing more for you! Good day!</Text>
    <Text id="pearNameTxt">Pear</Text>
    <Text id="appleNameTxt">Apple</Text>
    <Text id="pearDescTxt">This is a nice pear. Looks tasty!</Text>
    <Text id="appleDescTxt">This is a nice apple. Looks tasty!</Text>
    <Text id="eatPearMenuTxt">Eat the pear!</Text>
    <Text id="eatAppleMenuTxt">Eat the apple!</Text>
    <Text id="eatPearTxt">You have eaten the pear. Hmmm. It was reeaaaly good!</Text>
    <Text id="eatAppleTxt">##NOPE##</Text>
    <Text id="noMoreFruiteTxt">I am syrious! You get nothing more!</Text>
    <Text id="lookAtMenuTxt">I look it closer...</Text>
    <Text id="lookAtResponseTxt">The blacksmith is really ugly indeed... But there is a bucket next to him, full of nice fruits.</Text>
    <Text id="lookAtLaterResponseTxt">Now he doesn't seem so nice... I think he doesn't want me near anymore.</Text>
    <Text id="bigRoomNameTxt">Big room</Text>
    <Text id="bigRoomDescTxt">This is a biger room with a table in the middle, there is a paper on it.</Text>
    <Text id="paperNameTxt">Paper on the table</Text>
    <Text id="readPaparMenuTxt">Read</Text>
    <Text id="paperDescTxt">You read the following on the paper:\n"This was the first testgame for the Join-the-Adventure!\nThank you for tryin' it!"</Text>
    <Text id="neigbourBigToSmallMenuTxt">Back to the small room</Text>
    <Text id="npcBlacksmithNameTxt">Blacksmith</Text>
    <!--<Text id="npcBlacksmithDescTxt">The blackmisth is standing in the other part of the room. By the way, he is really ugly.</Text> -->
    <Text id="gameNameTxt">Awesome Test Game</Text>
    <Text id="gameDescTxt">This is only a test game.</Text>
    <Text id="appleDeathTxt">The apple was great. But when u finish with the last bite, you can feel something wrong.\nSuddenly you fall down dead.\nGame Over.</Text>
    <Text id="gameOverTxt">GAME OVER</Text>
    <Text id="jtaLabelInventory">Backpack</Text>
    <Text id="jtaLabelGoNextRoom">Go further...</Text>
    <Text id="jtaLabelMenu">Menu</Text>
    <Text id="jtaLabelPickUp">Take it</Text>
    <Text id="jtaLabelBack">Back</Text>
    <Text id="jtaLabelItems">Items</Text>
    <Text id="jtaLabelPickUpNotif">You have taken the</Text>
    <Text id="jtaLabelNpc">Npcs</Text>
    <Text id="jtaLabelShowDescription">Make a better look...</Text>
    <Text id="jtaLabelStartConversation">Start conversation</Text>
    <Text id="jtaLabelConversationWith">Conversation with </Text>
  </Texts>
</GameDescriptor>

=== hbalazs11/Join-the-Adventure/games/probafred/FredInSpace.xml
<?xml version="1.0" encoding="utf-8"?>
<GameDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="JtaDescriptor.xsd"
                gameName="probafred"
                version="v1.0" >
  <GameProperties firstRoomId="Spaceship" defaultLang="hun" greetingTextId="gameGreetingTxt" menuSaveAvailable="false" checkpointsOn="false" gameNameTextId="gameNametxt" menuImgSrc="menuImg.jpg"/>
  <Rooms>
    <Room id="Spaceship" activeAtStart="true" nameTextId="spaceshipNameTxt" descTextId="spaceshipDescTxt" imgSrc="spaceship.jpg">
      <Texts>
        <Text id="spaceshipNameTxt">Fred hajója</Text>
        <Text id="spaceshipDescTxt">Egy átlagos kisméretű teherszállító hajó. Fred még a ballagására kapta. Az óvodásra.</Text>
      </Texts>
    </Room>
  </Rooms>
  <Texts>
    <Text id="gameGreetingTxt">Egy történet az űrben. Egy történet Fredről. Egy történet, melynek nincs se eleje, se vége.\nDe benne van Fred.</Text>
    <Text id="gameNametxt">Fred in Space</Text>
  </Texts>
</GameDescriptor>
